server:
  port: 9001
spring:
  application:
    name: shop-user-service
  rabbitmq:
    host: 192.168.253.17
    port: 5672
    virtual-host: /
    password: guest
    username: guest
    #开启手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
  cloud:
    #注册中心地址
    nacos:
      discovery:
        server-addr: localhost:8848
  # 避免使用swagger报错问题
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.253.17:3306/xd_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: liuche
# 整合redis
  redis:
    password: liuche
    host: 192.168.253.17
    port: 6379
    database: 1
    redisson-database: 2 # redisson使用的数据库
  #邮箱服务配置
  mail:
    host: smtp.qq.com # 配置邮件服务器的地址
    port: 465 # 配置邮件服务器的端口（465或587）
    username: 706716852@qq.com # 配置用户的账号
    password: zkftijvagbynbdgg # 配置用户的密码（即申请到的授权码）
    default-encoding: UTF-8 # 配置默认编码
    protocol: smtp
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory # SSL 连接配置
        debug: true # 开启 debug，这样方便开发者查看邮件发送日志



#配置plus打印sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
#logging:
#  level:
#    root: INFO
